### PR TITLE
Minor typo edit

### PR DESCRIPTION
**Pull request by swinslow**
Fix "copyring" => "copying"

Sent a signed ICLA to the FINOS address a couple of minutes ago  😄

### CODE REVIEW

**Comment by finos-admin** [comment]
Thank you for your pull request and welcome to our community! We require contributors to sign a [Contributor License Agreement](https://finosfoundation.atlassian.net/wiki/spaces/FINOS/pages/75530375/Legal+Requirements#LegalRequirements-ContributorLicenseAgreement) and we don't seem to have CLAs on file for these contributors to the Pull Request: (@swinslow). In order for your PR to be reviewed and merged, please follow the directions at the link above.

Project team: please **do not merge this Pull Request** until Foundation staff have confirmed that a CLA is in place for the new contributor(s) listed above.

If there are any questions, please don't hesitate to [get in touch with our Infrastructure Support team](https://finosfoundation.atlassian.net/wiki/spaces/FINOS/pages/77955298/Getting+in+Touch#GettinginTouch-InfrastructureSupport). /CC @finos-admin

**Comment by swinslow** [comment]
Hi @finos-admin, I had emailed a signed CLA earlier this month (on or around May 2) -- any progress on getting it pulled in and confirmed? Thank you!

**Comment by maoo** [comment]
@finos-cla-bot[bot] check

**Comment by finos-admin** [comment]
The cla-bot has been summoned, and re-checked this pull request!

**Comment by maoo** [comment]
@swinslow , apologies for the late notification, the CLA was correctly configured 16 days ago and - since then - your Pull Requests will be marked with a `cla-present` label. Please let me know if you have any further question, and feel free to reach out help@finos.org for any further question or issue.

Thanks!

**Comment by swinslow** [comment]
Fantastic and no worries, thank you @maoo!

**Pull request merged**
